
variable "ENABLE_FEEDBACK_SUBMISSION"{}


variable "DEVELOPMENT_MODE"{}

variable "NODE_ENV"{}

variable "ENV"{}
variable "ACCOUNT_REGISTRATION_MODE"{}

variable "CUSTOM_DOMAIN_NAME"{}


variable "COGNITO_ADMIN_GROUP_DESCRIPTION"{}
variable "COGNITO_REGISTERED_GROUP_DESCRIPTION"{}

variable "HOSTED_ZONE_ID"{}
variable "USE_ROUTE53"{}

variable "ORIGIN_ID"{}
variable "ACM_CERTIFICATE_ARN"{}  

variable "COGNITO_USER_POOL_DOMAIN"{}

variable "ALLOW_ADMIN_CREATE_USER_ONLY"{}
